language: python
python: '3.6'
cache:
  yarn: true
  pip: true
  directories:
  - node_modules
install:
- yarn install
- yarn run build
- pip install .
script:
- echo "no tests implemented"
deploy:
  - provider: npm
    email: reevejamesd@gmail.com
    api_key:
      secure: V27ALzzuv/O3aI1/YHyuNW7mOSaSxyd2b7/4yZhku2yKeLGidA646+KsUSfJiI+ghZWqwO+Nat0L4CKQwVahim7/f54D/wbY6m0hSdZr7w0W3SekLqXQY+LYSbIs1fkwGJ0WDWO0q6SVY0WgK4pcLcRhcQF3dC22yKwSEXZuY+2pzFg7nQacmWM5djwFvsser3VxnIpoK9F4w7og2l5H1plWjcEZbLyNzWv7y05T4C+FOBUEHajYFILi3ohI/lSfYqRza8tx7LFiec58aV6XRHWPkyYWjg0MzZvkYX22PSAger5mR1rXpExDHjkBWbLLf+kJFSV37yIzYzWviQYy9dJYj0p9BDIBpQevz1yAsC8OsECfgewm75RZv1RLiIkpry+P+GConl9cdYbtfJmyRkftOnhyOPvFuROyWCzp+FWMAhQOxxHYue9nFAE74jtdtfKC8yeIKi6bJrVVd0ThlzDx1I3DlDUVPDDVyFeGVKbU43XTQKnmbZtBWGE51MKOFiFTAsjbm4UljhVoJokHEaLe0uYcCDWLXYIyTD3Od+azh3cIAGw4IBC1hgVB2AZp8U0YxTH5cTycQSOPJ1peoSrrOOC8Hn07d8tte/jFDl8ZmmR+ZbQukj8FGArri+FnKESrbz+XN+QAtREG+l9pEhxpnNsVv4kkRHLLa9x5JCU=
    skip_cleanup: true
    on:
      tags: true
      repo: IBM/jupyterlab-cognos-dashboard-embedded
  - provider: pypi
    user: __token__
    password:
      secure: D6Nvt3WEwLKOk0g/3ec22EztQLoUPpgFdFEa5HJOj4W2El4jNtasfk/x3HqBR9BNpnSL7yNRPWkFsHbUXsRF523310gUT+z31bLV+7kc9WqYgKgUlKf2cEtYHgzfgb4e4rXV6GrSSLTGN9SOKnckse6PogIT5iZWc6KBSUOklZssOIhBC7IPQtZQ5YZNJifRyOYlIfEZ59Firmq2YV+awazpU+Y7KTLbdOQ6SCI85CfojdMbTQhldwpGVxZNlFfoqjzpzoNnq3P8cQwHf5oLlFAxT+lnv0WibIswxyGn3Wx+qhLZP0MUbTfnvL1PEr1sQ7TrISPh0A6s5nrdX7ZpScxzm67MiBYt649hWFHboqngX4O7HIRGoMebNfXh+8sOeHdDJL86DOQoMejg6Oe5rmdy48rwELUrboOmXB18jQibXuMOD5uzGunWa5UH6FEroh1nCY+9g1qxV28zjy7iIbZuUOpO+6WovNRjWeU49TpOF6PU3kT/3IJiVQ7SCCg9haWwSGke6x1PQ9i2y+wIA2hBcbE53dgaRY4QKlzse5ROsiaXsf/aecIwSJbaTt+uq5F7kJDMAn3yScZKFRo6ZK7ty1mya2BukV4NKfdVPCG9uRR2amCtR5NbumomYOgLT6bfx4uMzlygNJnyYF2gu1KWF4iA8rtDCOmAqFko1/s=
    skip_cleanup: true
    on:
      tags: true
      repo: IBM/jupyterlab-cognos-dashboard-embedded
