language: python
python: '3.6'
cache:
  yarn: true
  pip: true
  directories:
    - node_modules
install:
  - yarn install
  - yarn run build
  - pip install .
script:
  - echo "no tests implemented"
deploy:
  - provider: script
    skip_cleanup: true
    script: "cp .npmrc.template $HOME/.npmrc && npm publish"
    on:
      repo: skills-network-labs/jupyterlab-cognos-dashboard-embedded
      tags: true
  - provider: pypi
    skip_cleanup: true
    server: https://na.artifactory.swg-devops.com/artifactory/api/pypi/apset-pypi-local
    user: james.reeve@ibm.com
    password:
      secure: "O5/P31fW8iL3uBTSMzQRxnFwcrKbiY6+vpkHag1fjfjkg7vgTx8VZlrmFSwW1dzz6Xslevsd4cuDBLUl9qqI+ICACF2PQWYqTB5GnWWsAv6BQJabhDyow0tO5IbEk3AjSZr3atLm16ULb94QhesAMuHb2/bxfnrHDoq4tM06bCW6fjdKq+GiCfr5tF1otbeCu2+bntzJ7rvjQQW3vZIREJOmn5lzb3BsBCBPHeCTjliFV0/zDAEBscwhlK72TenOg+XVgqqAMXPyIMZg498alYjSpXIK1pc0FiHrRo5G8pJj0Hc4w8CfxGLL1JUao35Jk/mOG7FaYVrQOY5kVcbL1901chO8h5q99aMhWJ8LqbyM9uBsRb+nbXQTQIXKmQzgyf01M+i3lIvOu9u/vww6WoVjE9og8oIdXWX6FWQ5XxV4wlaFQkrduKcvI2dqGIyWCmB9Q+fmLo+zy11eAXNzw8pXuog5s/XEHyAKLwrxDZo1C3WDiNrnsMNSJwsfFXU212KXLJDS3m9nkQxbhoRZIkV/P3vkAlM4vIs2ugXMaJZbhEigOnSW5qfDpG4wPosreWsnPUglfOBJu8khhX7ZVnonNrbjLuEl8C7l+RXshSrtflWl+iq1RhWxdePi4mRMfcIpSu2KgKdmqD5DgoCatxR7F6dbOYYRLxvqxWPP8QM="
    on:
      repo: skills-network-labs/jupyterlab-cognos-dashboard-embedded
      tags: true
notifications:
  email: false
  slack:
    on_pull_requests: false
    on_failure: "change"
    on_success: "change"
    secure: "4BKLFsMrsh6+IeGhoN+pgrrXfhV5O6xXDMSfEs96ZXs7pSNHrmchrbRESMky/V5R5TCDQbMCzZxYSRUeUM0JLCKDSITke5B3Rcu24ELxqYEqNyd+OWeMhpxObVU6hHOvl2y6aEYLACkuvezS+/r75rgnbtHNYXhq+kGcNw8Vh9uKeJ0EZ87pG5DDDrILN3db2HxPBeelBDP3iLis66Ni5x9aFxs66EmK99UV3nqbSvCjuvWzFrg5LsDOb8jKvYYffjgSMe/oyAxOYhSbBP2/TLohXlPzORc98qIYLy8rbynzTM7vQrtN1skiNslhabbhmvqZdX9+EPSqwZpA15nMFI3DX62L5Tu6SRkGXlfsWIXsoJnHThDs4EGiDrNRS3NCs/761GKTV4fcdCTLk0rssJNeNYPh4p0c2jGKZCbgWoRRhn3vjk6nxVZgjOVbpqAYfeDufiMtylh9B9lW6hCKC9ELrbRw8f6TjZN/dqinjVqXB9tdseYyV0R/vFyKMsHm9AD3CZ8EuxwxsrHVGJJTM5+s165xRfVRnDvnmKOWrqltJi0AA+2xkPh50F96WSe+iXaoVvqYM/V3QrvwQAPR9Ay6Hgqu6c0Obn2OOTgzTRIYPJg+8To77a+REqSyI1JfPOB+GRfvbcTywt2W6xeworgGvGS/sRkdFrn0OFbQ8fI=" # pragma: whitelist secret
