language: python
python: '3.6'
cache:
  yarn: true
  pip: true
  directories:
    - node_modules
install:
  - yarn install
  - yarn run build
  - pip install .
script:
  - echo "no tests implemented"
deploy:
  - provider: script
    skip_cleanup: true
    script: "cp .npmrc.template $HOME/.npmrc && npm publish"
    on:
      repo: cognitive-class-labs/jupyterlab-cognos-dashboard-embedded
      tags: true
  - provider: pypi
    skip_cleanup: true
    server: https://na.artifactory.swg-devops.com/artifactory/api/pypi/apset-pypi-local
    user: james.reeve@ibm.com
    password:
      secure: m9cWNcnYVKkKwORzDrpGZD5oQCKC0GhD7D3DXHb5Pf/TBczTAaacfVdpGuE2NFA6bfspCewiX89+g1BGn/yb4T9HDyuq+RlNlRQK6oDk6bYyNamn0TTZYb0xd7yg3y6pJhzk78V1ZBWeTb6ATgu0KGPhuH//wQbWPEvCFmqADKDQvtkdulxKhkUo9IAPXpK9yCJONrCSfAIxXjGtn0tWBBtwmEWw9+wmls8FABj+b8r1vIJtMA3h+VGX2DDJmTSn/r9FCx8lknHSSI7rVQu00nU6L9LkqPKfeEUbDmdTJXFIDFOcVsgmWzOpIWBikrnr8pSKymqsKHxXv6r7f6e9ioioaYiDVvWjsTwo/0NXNZSaynRbQDJJoE7hPXmIQOGmxYCDN54azz9LYHPtOUcd2BnPZKBM3miA4eXCyCyaim6BTsL78UZVjURgQ78eVGrDJnhOgmzbrlnJJVSQWsNIwyuF2OfCTJWkjl7gsXOjlsICcvNi6O6A/Lf7JJsUh+ixvflFXHFnwKiM3CAN8or3IR4Il1pfJxjVBmIxyeUyy8m7ht5TTSKZJSrMQYtl2zjVHR+td8xU1qctdl/iNEEXpAUejZTQlmPALpI44lSiEFzIrMcioREmd3iqBCDZG1tjWuKfVG3GRXH+LZuGtWo70xjr84rTdw6tE5fB+GqoK0Q=
    on:
      repo: cognitive-class-labs/jupyterlab-cognos-dashboard-embedded
      tags: true
notifications:
  email: false
  slack:
    on_pull_requests: false
    on_failure: "change"
    on_success: "change"
    secure: "4BKLFsMrsh6+IeGhoN+pgrrXfhV5O6xXDMSfEs96ZXs7pSNHrmchrbRESMky/V5R5TCDQbMCzZxYSRUeUM0JLCKDSITke5B3Rcu24ELxqYEqNyd+OWeMhpxObVU6hHOvl2y6aEYLACkuvezS+/r75rgnbtHNYXhq+kGcNw8Vh9uKeJ0EZ87pG5DDDrILN3db2HxPBeelBDP3iLis66Ni5x9aFxs66EmK99UV3nqbSvCjuvWzFrg5LsDOb8jKvYYffjgSMe/oyAxOYhSbBP2/TLohXlPzORc98qIYLy8rbynzTM7vQrtN1skiNslhabbhmvqZdX9+EPSqwZpA15nMFI3DX62L5Tu6SRkGXlfsWIXsoJnHThDs4EGiDrNRS3NCs/761GKTV4fcdCTLk0rssJNeNYPh4p0c2jGKZCbgWoRRhn3vjk6nxVZgjOVbpqAYfeDufiMtylh9B9lW6hCKC9ELrbRw8f6TjZN/dqinjVqXB9tdseYyV0R/vFyKMsHm9AD3CZ8EuxwxsrHVGJJTM5+s165xRfVRnDvnmKOWrqltJi0AA+2xkPh50F96WSe+iXaoVvqYM/V3QrvwQAPR9Ay6Hgqu6c0Obn2OOTgzTRIYPJg+8To77a+REqSyI1JfPOB+GRfvbcTywt2W6xeworgGvGS/sRkdFrn0OFbQ8fI=" # pragma: whitelist secret
