language: python
python: '3.6'
cache:
  yarn: true
  pip: true
  directories:
    - node_modules
install:
  - yarn install
  - yarn run build
  - pip install .
script:
  - echo "no tests implemented"
deploy:
  - provider: script
    skip_cleanup: true
    script: "cp .npmrc.template $HOME/.npmrc && npm publish"
    on:
      repo: skills-network-labs/jupyterlab-cognos-dashboard-embedded
      tags: true
  - provider: pypi
    skip_cleanup: true
    server: https://na.artifactory.swg-devops.com/artifactory/api/pypi/apset-pypi-local
    user: james.reeve@ibm.com
    password:
      secure: p5Yqh5gfQif4XxgEU/dKrUYSXCkavsJ9MqrYfzvfMz7aTj3yWESgYzd89X7KOKuVwdmMwCBBCEUpyRuCvfVGDajE7YwpLfPGrsd2YVer7B7K+G5mc7i7+DzeWGpNn+mHB0CnURGoSHMGmzvrEZZUFd514urIm51aRJCg2NBZX+QsuNYGT1f3WZccr8PU8e7NcFwA3SH/qjXSyUQtT80uonVMUHHMDzQGKlPfnFpw9Q2LMwgqYzjZ9VrHbPQDsYcPmrc6VEHghZVdxhfTWJCo387i3sqZGVwTM7pOLUiFzInxMjWV8UtoeR9q9gi+flqSuUYhMmcylRdsilXyZIl5EuLB0l1tC53Zx2zD2TkmxX8ft7rbbQ2QetyMpflYxKYUqNnjSIu2IeiOUaviNCSGV7zUYRCU3TJ3Mxr2AIylRTWdRq5KkpK5jicH+xoLTgMKn5fQ3RLtXnAkKOv6AIuSVZRph8CziWMp8haeTLnNaV+JSndXuEAWrYyRXQ+c3/PHw76B8JKTc5uK80qGnwmAOO/X/idXdqtHagz2lbn6mmd/JLFCtVc3KC9oQg3LQf/Ebix9PFtotO2WXl4Elbh13Xyh3dqIoWRBKL0WmG6W8E6WcxBJrj/vFEv0ukCuHnedfzEIVdlM9fDLchU4HINTxMO+EP1tEMNUlmjPGOQCEOc
    on:
      repo: skills-network-labs/jupyterlab-cognos-dashboard-embedded
      tags: true
notifications:
  email: false
  slack:
    on_pull_requests: false
    on_failure: "change"
    on_success: "change"
    secure: "4BKLFsMrsh6+IeGhoN+pgrrXfhV5O6xXDMSfEs96ZXs7pSNHrmchrbRESMky/V5R5TCDQbMCzZxYSRUeUM0JLCKDSITke5B3Rcu24ELxqYEqNyd+OWeMhpxObVU6hHOvl2y6aEYLACkuvezS+/r75rgnbtHNYXhq+kGcNw8Vh9uKeJ0EZ87pG5DDDrILN3db2HxPBeelBDP3iLis66Ni5x9aFxs66EmK99UV3nqbSvCjuvWzFrg5LsDOb8jKvYYffjgSMe/oyAxOYhSbBP2/TLohXlPzORc98qIYLy8rbynzTM7vQrtN1skiNslhabbhmvqZdX9+EPSqwZpA15nMFI3DX62L5Tu6SRkGXlfsWIXsoJnHThDs4EGiDrNRS3NCs/761GKTV4fcdCTLk0rssJNeNYPh4p0c2jGKZCbgWoRRhn3vjk6nxVZgjOVbpqAYfeDufiMtylh9B9lW6hCKC9ELrbRw8f6TjZN/dqinjVqXB9tdseYyV0R/vFyKMsHm9AD3CZ8EuxwxsrHVGJJTM5+s165xRfVRnDvnmKOWrqltJi0AA+2xkPh50F96WSe+iXaoVvqYM/V3QrvwQAPR9Ay6Hgqu6c0Obn2OOTgzTRIYPJg+8To77a+REqSyI1JfPOB+GRfvbcTywt2W6xeworgGvGS/sRkdFrn0OFbQ8fI=" # pragma: whitelist secret
